### ISSUE TITLE
missing a dismissPeekViewHandler

### ISSUE THREAD

**Issue by Dandiccf** [itsmeichigo/PeekView#10]
I need to execute some code whenever PeekView is dismissed.

Could you please add a 'dismissPeekViewHandler' parameter in your configureView function which is executed whenever the PeekView is dismissed, or something similar?

thx

**Comment by csemresari** [comment]
I agree with Dandiccf.

I strongly need a completion handler to perform a task after dismissing the PeekView.

Thank you.

**Comment by itsmeichigo** [comment]
Hi, sorry for the delay in response. I've updated the source code and pushed the changes, hope it's helpful for you guys.

**Comment by Dandiccf** [comment]
Hi there,  works perfectly - thx
