### ISSUE TITLE
Swift 2.3 | 3

### ISSUE THREAD

**Issue by alejandrorbradford** [itsmeichigo/PeekView#6]
Is this updated to Swift 3 or 2.3?

**Comment by itsmeichigo** [comment]
Hi, an update is being made for Swift3 migration.

**Comment by alejandrorbradford** [comment]
Thank you, when would it be released?

**Comment by itsmeichigo** [comment]
In at most 2 days I guess. Thanks for the patience :]

**Comment by itsmeichigo** [comment]
Everything's up and running now, you can clone new code or update pod if you use Swift 3. As for Swift 2.3, check out branch `swift23`.
